# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'latest'
  buildConfiguration: 'Release'

stages:
- stage: 'Test&Push'
  displayName: 'Run tests and push to container registry'
  jobs:
  - job: 'Test'
    displayName: 'Test job'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK v5.x'
      inputs:
        version: '5.x'
    - task: DotNetCoreCLI@2
      displayName: 'Run Unit Tests - $(buildConfiguration)'
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
  - job: 'Push'
    displayName: 'Push image to container registry'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'BikeStoreWebApi20230221003632'
        repository: 'bikestorewebapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'