# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'latest'
  buildConfiguration: 'Release'

stages:
- stage: 'Test'
  displayName: 'Run tests'
  jobs:
  - job: 'Test'
    displayName: 'Test job'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK v5.x'
      inputs:
        version: '5.x'
    - task: DotNetCoreCLI@2
      displayName: 'Run Unit Tests - $(buildConfiguration)'
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'