version: '3.4'

networks:
    bikestore_backend:

services:
  demodatabase:
    container_name: demodatabase
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Pa55word1
    networks:
        - bikestore_backend
    ports:
        - 1433:1433
    volumes:
        - sqldatavolume:/var/opt/mssql
  bikestorewebapi:
    container_name: demo-bike-store-api
    image: ${DOCKER_REGISTRY-}bikestorewebapi
    build:
        context: .
        dockerfile: BikeStoreWebApi/Dockerfile
    depends_on:
        - demodatabase
    environment:
        - DB_HOST=demodatabase
        - DB_NAME=BikeStoreWebApi
        - DB_SA_PASSWORD=Pa55word
    networks:
        - bikestore_backend
volumes:
  sqldatavolume: